# -*- coding: utf-8 -*-
"""서울 지하철 1~9호선 전 역 구조 데이터(slug·역명·노선·자치구).

slug·역명·노선은 역 정보에서 추출, 자치구는 행정동/대표역 매핑으로 산출.
본문은 build 단계에서 노선·자치구·같은 노선 역 정보를 바탕으로 새로 생성한다.
도어웨이 방지: 노선·인접·자치구 등 실제 구조 정보로 페이지를 차별화한다.
"""

ALL_STATIONS = [
    {"slug":"achasan-station","name":"아차산역","lines":['5호선'],"gu":None},
    {"slug":"aeogae-station","name":"애오개역","lines":['5호선'],"gu":None},
    {"slug":"ahyeon-station","name":"아현역","lines":['2호선'],"gu":"mapo-gu"},
    {"slug":"airport-market-station","name":"공항시장역","lines":['9호선'],"gu":"gangseo-gu"},
    {"slug":"amsa-station","name":"암사역","lines":['8호선'],"gu":"gangdong-gu"},
    {"slug":"anam-station","name":"안암역","lines":['6호선'],"gu":"seongbuk-gu"},
    {"slug":"anguk-station","name":"안국역","lines":['3호선'],"gu":"jongno-gu"},
    {"slug":"apgujeong-rodeo-station","name":"압구정로데오역","lines":['수인분당선'],"gu":"gangnam-gu"},
    {"slug":"apgujeong-station","name":"압구정역","lines":['3호선'],"gu":"gangnam-gu"},
    {"slug":"balsan-station","name":"발산역","lines":['5호선'],"gu":"gangseo-gu"},
    {"slug":"bangbae-station","name":"방배역","lines":['2호선'],"gu":"seocho-gu"},
    {"slug":"banghak-station","name":"방학역","lines":['1호선'],"gu":"dobong-gu"},
    {"slug":"banghwa-station","name":"방화역","lines":['5호선'],"gu":"gangseo-gu"},
    {"slug":"bangi-station","name":"방이역","lines":['5호선'],"gu":"songpa-gu"},
    {"slug":"banpo-station","name":"반포역","lines":['7호선'],"gu":"seocho-gu"},
    {"slug":"beotigogae-station","name":"버티고개역","lines":['6호선'],"gu":"jung-gu"},
    {"slug":"bohun-hospital-station","name":"중앙보훈병원역","lines":['9호선'],"gu":"gwanak-gu"},
    {"slug":"bokjeong-station","name":"복정역","lines":['8호선'],"gu":"songpa-gu"},
    {"slug":"bomun-station","name":"보문역","lines":['우이신설선'],"gu":"seongbuk-gu"},
    {"slug":"bongcheon-station","name":"봉천역","lines":['2호선'],"gu":"gwanak-gu"},
    {"slug":"bongeunsa-station","name":"봉은사역","lines":['9호선'],"gu":"gangnam-gu"},
    {"slug":"bonghwasan-station","name":"봉화산역","lines":['6호선'],"gu":None},
    {"slug":"boramae-station","name":"보라매역","lines":['7호선'],"gu":"gwanak-gu"},
    {"slug":"bulgwang-station","name":"불광역","lines":['3호선', '6호선'],"gu":"eunpyeong-gu"},
    {"slug":"buramsan-station","name":"불암산역","lines":['4호선'],"gu":None},
    {"slug":"changdong-station","name":"창동역","lines":['4호선'],"gu":"dobong-gu"},
    {"slug":"changsin-station","name":"창신역","lines":['6호선'],"gu":"jongno-gu"},
    {"slug":"cheongdam-station","name":"청담역","lines":['7호선'],"gu":"gangnam-gu"},
    {"slug":"cheonggu-station","name":"청구역","lines":['6호선'],"gu":"jung-gu"},
    {"slug":"cheongho-station","name":"천호역","lines":['5호선', '8호선'],"gu":"gangdong-gu"},
    {"slug":"cheongnyangni-station","name":"청량리역","lines":['1호선', '수인분당선', '경의중앙선', '경춘선'],"gu":"dongdaemun-gu"},
    {"slug":"childrens-grand-park-station","name":"어린이대공원역","lines":['7호선'],"gu":"gwangjin-gu"},
    {"slug":"chungjeongno-station","name":"충정로역","lines":['5호선'],"gu":"seodaemun-gu"},
    {"slug":"chungmuro-station","name":"충무로역","lines":['4호선'],"gu":"jung-gu"},
    {"slug":"city-hall-station","name":"시청역","lines":['1호선', '2호선'],"gu":None},
    {"slug":"daebang-station","name":"대방역","lines":['1호선'],"gu":"dongjak-gu"},
    {"slug":"daecheong-station","name":"대청역","lines":['3호선'],"gu":None},
    {"slug":"daechi-station","name":"대치역","lines":['3호선'],"gu":"gangnam-gu"},
    {"slug":"daeheung-station","name":"대흥역","lines":['6호선'],"gu":"mapo-gu"},
    {"slug":"daerim-station","name":"대림역","lines":['7호선'],"gu":"guro-gu"},
    {"slug":"dangsan-station","name":"당산역","lines":['2호선', '9호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"dapsimni-station","name":"답십리역","lines":['5호선'],"gu":"dongdaemun-gu"},
    {"slug":"ddp-station","name":"동대문역사문화공원역","lines":['5호선'],"gu":"jung-gu"},
    {"slug":"deungchon-station","name":"등촌역","lines":['9호선'],"gu":"gangseo-gu"},
    {"slug":"dmc-station","name":"디지털미디어시티역","lines":['공항철도'],"gu":"mapo-gu"},
    {"slug":"dobong-station","name":"도봉역","lines":['1호선'],"gu":"dobong-gu"},
    {"slug":"dobongsan-station","name":"도봉산역","lines":['1호선', '7호선'],"gu":"dobong-gu"},
    {"slug":"dogok-station","name":"도곡역","lines":['수인분당선'],"gu":"gangnam-gu"},
    {"slug":"dokbawi-station","name":"독바위역","lines":['6호선'],"gu":None},
    {"slug":"doksan-station","name":"독산역","lines":['1호선'],"gu":"geumcheon-gu"},
    {"slug":"dolgoji-station","name":"돌곶이역","lines":['6호선'],"gu":None},
    {"slug":"dongdaemun-station","name":"동대문역","lines":['4호선'],"gu":None},
    {"slug":"dongguk-univ-station","name":"동대입구역","lines":['3호선'],"gu":None},
    {"slug":"dongjak-station","name":"동작역","lines":['9호선'],"gu":None},
    {"slug":"dongmyo-station","name":"동묘앞역","lines":['6호선'],"gu":None},
    {"slug":"dongnimmun-station","name":"독립문역","lines":['3호선'],"gu":"seodaemun-gu"},
    {"slug":"dorimcheon-station","name":"도림천역","lines":['2호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"dunchon-oryun-station","name":"둔촌오륜역","lines":['9호선'],"gu":"gangdong-gu"},
    {"slug":"dunchondong-station","name":"둔촌동역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"eonju-station","name":"언주역","lines":['9호선'],"gu":"gangnam-gu"},
    {"slug":"euljiro-entrance-station","name":"을지로입구역","lines":['2호선'],"gu":"jung-gu"},
    {"slug":"euljiro3ga-station","name":"을지로3가역","lines":['3호선'],"gu":"jung-gu"},
    {"slug":"euljiro4ga-station","name":"을지로4가역","lines":['5호선'],"gu":"jung-gu"},
    {"slug":"eungam-station","name":"응암역","lines":['6호선'],"gu":"eunpyeong-gu"},
    {"slug":"gaebong-station","name":"개봉역","lines":['1호선'],"gu":"guro-gu"},
    {"slug":"gaehwa-station","name":"개화역","lines":['9호선'],"gu":None},
    {"slug":"gaehwasan-station","name":"개화산역","lines":['5호선'],"gu":None},
    {"slug":"gaerong-station","name":"개롱역","lines":['5호선'],"gu":None},
    {"slug":"gangbyeon-station","name":"강변역","lines":['2호선'],"gu":"gwangjin-gu"},
    {"slug":"gangdong-gu-office-station","name":"강동구청역","lines":['8호선'],"gu":"gangdong-gu"},
    {"slug":"gangdong-station","name":"강동역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"gangil-station","name":"강일역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"gangnam-gu-office-station","name":"강남구청역","lines":['7호선'],"gu":"gangnam-gu"},
    {"slug":"gangnam-station","name":"강남역","lines":['2호선', '신분당선', '분당선'],"gu":"gangnam-gu"},
    {"slug":"garak-market-station","name":"가락시장역","lines":['3호선', '8호선'],"gu":"songpa-gu"},
    {"slug":"gasan-digital-complex-station","name":"가산디지털단지역","lines":['1호선', '7호선'],"gu":"geumcheon-gu"},
    {"slug":"gayang-station","name":"가양역","lines":['9호선'],"gu":"gangseo-gu"},
    {"slug":"geondae-entrance-station","name":"건대입구역","lines":['2호선', '7호선'],"gu":"gwangjin-gu"},
    {"slug":"geoyeo-station","name":"거여역","lines":['5호선'],"gu":"songpa-gu"},
    {"slug":"geumcheon-gu-office-station","name":"금천구청역","lines":['1호선'],"gu":"geumcheon-gu"},
    {"slug":"geumho-station","name":"금호역","lines":['3호선'],"gu":"seongdong-gu"},
    {"slug":"gildong-station","name":"길동역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"gimpo-airport-station","name":"김포공항역","lines":['5호선', '9호선', '공항철도'],"gu":"gangseo-gu"},
    {"slug":"gireum-station","name":"길음역","lines":['4호선'],"gu":"seongbuk-gu"},
    {"slug":"godeok-station","name":"고덕역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"gongdeok-station","name":"공덕역","lines":['5호선', '6호선', '경의중앙선', '공항철도'],"gu":"mapo-gu"},
    {"slug":"gongneung-station","name":"공릉역","lines":['7호선', '경춘선'],"gu":"nowon-gu"},
    {"slug":"gosok-terminal-station","name":"고속터미널역","lines":['3호선', '7호선', '9호선'],"gu":"seocho-gu"},
    {"slug":"gubanpo-station","name":"구반포역","lines":['9호선'],"gu":"seocho-gu"},
    {"slug":"gubeundari-station","name":"굽은다리역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"guil-station","name":"구일역","lines":['1호선'],"gu":None},
    {"slug":"gunja-station","name":"군자역","lines":['5호선', '7호선'],"gu":None},
    {"slug":"gupabal-station","name":"구파발역","lines":['3호선'],"gu":"eunpyeong-gu"},
    {"slug":"guro-digital-complex-station","name":"구로디지털단지역","lines":['2호선'],"gu":"guro-gu"},
    {"slug":"guro-station","name":"구로역","lines":['1호선'],"gu":"guro-gu"},
    {"slug":"gusan-station","name":"구산역","lines":['6호선'],"gu":"eunpyeong-gu"},
    {"slug":"guui-station","name":"구의역","lines":['2호선'],"gu":"gwangjin-gu"},
    {"slug":"gwangheungchang-station","name":"광흥창역","lines":['6호선'],"gu":"mapo-gu"},
    {"slug":"gwanghwamun-station","name":"광화문역","lines":['5호선'],"gu":"jongno-gu"},
    {"slug":"gwangnaru-station","name":"광나루역","lines":['5호선'],"gu":None},
    {"slug":"gyeongbokgung-station","name":"경복궁역","lines":['3호선'],"gu":"jongno-gu"},
    {"slug":"gyodae-station","name":"교대역","lines":['2호선', '3호선'],"gu":"seocho-gu"},
    {"slug":"haengdang-station","name":"행당역","lines":['5호선'],"gu":"seongdong-gu"},
    {"slug":"hagye-station","name":"하계역","lines":['7호선'],"gu":"nowon-gu"},
    {"slug":"hakdong-station","name":"학동역","lines":['7호선'],"gu":None},
    {"slug":"hangangjin-station","name":"한강진역","lines":['6호선'],"gu":"yongsan-gu"},
    {"slug":"hangnyeoul-station","name":"학여울역","lines":['3호선'],"gu":"gangnam-gu"},
    {"slug":"hannam-station","name":"한남역","lines":['6호선'],"gu":"yongsan-gu"},
    {"slug":"hanseong-baekje-station","name":"한성백제역","lines":['9호선'],"gu":"songpa-gu"},
    {"slug":"hansung-univ-station","name":"한성대입구역","lines":['4호선'],"gu":"seongbuk-gu"},
    {"slug":"hanyang-univ-station","name":"한양대역","lines":['2호선'],"gu":None},
    {"slug":"hapjeong-station","name":"합정역","lines":['2호선', '6호선'],"gu":"mapo-gu"},
    {"slug":"heukseok-station","name":"흑석역","lines":['9호선'],"gu":"dongjak-gu"},
    {"slug":"hoegi-station","name":"회기역","lines":['경의중앙선'],"gu":"dongdaemun-gu"},
    {"slug":"hoehyeon-station","name":"회현역","lines":['4호선'],"gu":"jung-gu"},
    {"slug":"hongik-univ-station","name":"홍대입구역","lines":['2호선', '경의중앙선', '공항철도'],"gu":"mapo-gu"},
    {"slug":"hongje-station","name":"홍제역","lines":['3호선'],"gu":"seodaemun-gu"},
    {"slug":"hufs-station","name":"외대앞역","lines":['1호선'],"gu":"dongdaemun-gu"},
    {"slug":"hwagok-station","name":"화곡역","lines":['5호선'],"gu":"gangseo-gu"},
    {"slug":"hwarangdae-station","name":"화랑대역","lines":['6호선'],"gu":None},
    {"slug":"hyehwa-station","name":"혜화역","lines":['4호선'],"gu":"jongno-gu"},
    {"slug":"hyochang-park-station","name":"효창공원앞역","lines":['6호선'],"gu":"yongsan-gu"},
    {"slug":"ichon-station","name":"이촌역","lines":['1호선', '4호선'],"gu":"yongsan-gu"},
    {"slug":"idae-station","name":"이대역","lines":['2호선'],"gu":"seodaemun-gu"},
    {"slug":"irwon-station","name":"일원역","lines":['3호선'],"gu":"gangnam-gu"},
    {"slug":"isu-station","name":"이수역","lines":['7호선'],"gu":"dongjak-gu"},
    {"slug":"itaewon-station","name":"이태원역","lines":['6호선'],"gu":"yongsan-gu"},
    {"slug":"jamsil-saenae-station","name":"잠실새내역","lines":['2호선'],"gu":"songpa-gu"},
    {"slug":"jamsil-station","name":"잠실역","lines":['2호선', '8호선'],"gu":"songpa-gu"},
    {"slug":"jamsillaru-station","name":"잠실나루역","lines":['2호선'],"gu":"songpa-gu"},
    {"slug":"jamwon-station","name":"잠원역","lines":['3호선'],"gu":"seocho-gu"},
    {"slug":"janghanpyeong-station","name":"장한평역","lines":['5호선'],"gu":"dongdaemun-gu"},
    {"slug":"jangji-station","name":"장지역","lines":['8호선'],"gu":"songpa-gu"},
    {"slug":"jangseungbaegi-station","name":"장승배기역","lines":['7호선'],"gu":"dongjak-gu"},
    {"slug":"jayang-station","name":"자양역","lines":['7호선'],"gu":"gwangjin-gu"},
    {"slug":"jegidong-station","name":"제기동역","lines":['1호선'],"gu":"dongdaemun-gu"},
    {"slug":"jeungmi-station","name":"증미역","lines":['9호선'],"gu":"gangseo-gu"},
    {"slug":"jeungsan-station","name":"증산역","lines":['6호선'],"gu":"eunpyeong-gu"},
    {"slug":"jonggak-station","name":"종각역","lines":['1호선'],"gu":"jongno-gu"},
    {"slug":"jongno3ga-station","name":"종로3가역","lines":['1호선', '3호선', '5호선'],"gu":"jongno-gu"},
    {"slug":"jongno5ga-station","name":"종로5가역","lines":['1호선'],"gu":"jongno-gu"},
    {"slug":"junggok-station","name":"중곡역","lines":['7호선'],"gu":"gwangjin-gu"},
    {"slug":"junggye-station","name":"중계역","lines":['7호선'],"gu":"nowon-gu"},
    {"slug":"junghwa-station","name":"중화역","lines":['7호선'],"gu":"jungnang-gu"},
    {"slug":"kkachisan-station","name":"까치산역","lines":['5호선'],"gu":None},
    {"slug":"korea-univ-station","name":"고려대역","lines":['6호선'],"gu":"seongbuk-gu"},
    {"slug":"kwangwoon-univ-station","name":"광운대역","lines":['1호선'],"gu":None},
    {"slug":"macheon-station","name":"마천역","lines":['5호선'],"gu":"songpa-gu"},
    {"slug":"madeul-station","name":"마들역","lines":['7호선'],"gu":None},
    {"slug":"maebong-station","name":"매봉역","lines":['3호선'],"gu":None},
    {"slug":"magok-station","name":"마곡역","lines":['5호선'],"gu":"gangseo-gu"},
    {"slug":"magongnaru-station","name":"마곡나루역","lines":['공항철도'],"gu":"gangseo-gu"},
    {"slug":"majang-station","name":"마장역","lines":['5호선'],"gu":"seongdong-gu"},
    {"slug":"mangwon-station","name":"망원역","lines":['2호선'],"gu":"mapo-gu"},
    {"slug":"mapo-gu-office-station","name":"마포구청역","lines":['6호선'],"gu":"mapo-gu"},
    {"slug":"mapo-station","name":"마포역","lines":['5호선'],"gu":"mapo-gu"},
    {"slug":"meokgol-station","name":"먹골역","lines":['7호선'],"gu":None},
    {"slug":"mia-station","name":"미아역","lines":['4호선'],"gu":"gangbuk-gu"},
    {"slug":"miasageori-station","name":"미아사거리역","lines":['4호선'],"gu":"gangbuk-gu"},
    {"slug":"mokdong-station","name":"목동역","lines":['5호선'],"gu":"yangcheon-gu"},
    {"slug":"mongchontoseong-station","name":"몽촌토성역","lines":['8호선'],"gu":None},
    {"slug":"muakjae-station","name":"무악재역","lines":['3호선'],"gu":"seodaemun-gu"},
    {"slug":"mullae-station","name":"문래역","lines":['2호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"munjeong-station","name":"문정역","lines":['8호선'],"gu":"songpa-gu"},
    {"slug":"myeongdong-station","name":"명동역","lines":['4호선'],"gu":"jung-gu"},
    {"slug":"myeongil-station","name":"명일역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"myeonmok-station","name":"면목역","lines":['7호선'],"gu":"jungnang-gu"},
    {"slug":"naebang-station","name":"내방역","lines":['7호선'],"gu":None},
    {"slug":"nakseongdae-station","name":"낙성대역","lines":['2호선'],"gu":"gwanak-gu"},
    {"slug":"nambu-terminal-station","name":"남부터미널역","lines":['3호선'],"gu":"seocho-gu"},
    {"slug":"namguro-station","name":"남구로역","lines":['7호선'],"gu":"guro-gu"},
    {"slug":"namseong-station","name":"남성역","lines":['7호선'],"gu":None},
    {"slug":"namtaeryeong-station","name":"남태령역","lines":['4호선'],"gu":None},
    {"slug":"namyeong-station","name":"남영역","lines":['1호선'],"gu":"yongsan-gu"},
    {"slug":"national-assembly-station","name":"국회의사당역","lines":['9호선'],"gu":"dongjak-gu"},
    {"slug":"nodeul-station","name":"노들역","lines":['9호선'],"gu":"dongjak-gu"},
    {"slug":"nokbeon-station","name":"녹번역","lines":['3호선'],"gu":"eunpyeong-gu"},
    {"slug":"nokcheon-station","name":"녹천역","lines":['1호선'],"gu":None},
    {"slug":"noksapyeong-station","name":"녹사평역","lines":['6호선'],"gu":None},
    {"slug":"nonhyeon-station","name":"논현역","lines":['7호선'],"gu":"gangnam-gu"},
    {"slug":"noryangjin-station","name":"노량진역","lines":['1호선', '9호선'],"gu":"dongjak-gu"},
    {"slug":"nowon-station","name":"노원역","lines":['4호선', '7호선'],"gu":"nowon-gu"},
    {"slug":"ogeum-station","name":"오금역","lines":['5호선'],"gu":"songpa-gu"},
    {"slug":"oksu-station","name":"옥수역","lines":['경의중앙선'],"gu":"seongdong-gu"},
    {"slug":"olympic-park-station","name":"올림픽공원역","lines":['9호선'],"gu":None},
    {"slug":"omokgyo-station","name":"오목교역","lines":['5호선'],"gu":"yangcheon-gu"},
    {"slug":"onsu-station","name":"온수역","lines":['7호선'],"gu":None},
    {"slug":"oryudong-station","name":"오류동역","lines":['1호선'],"gu":"guro-gu"},
    {"slug":"police-hospital-station","name":"경찰병원역","lines":['3호선'],"gu":None},
    {"slug":"sadang-station","name":"사당역","lines":['2호선', '4호선'],"gu":"dongjak-gu"},
    {"slug":"saejeol-station","name":"새절역","lines":['6호선'],"gu":"eunpyeong-gu"},
    {"slug":"saetgang-station","name":"샛강역","lines":['9호선'],"gu":None},
    {"slug":"sagajeong-station","name":"사가정역","lines":['7호선'],"gu":"jungnang-gu"},
    {"slug":"samgakji-station","name":"삼각지역","lines":['6호선'],"gu":"yongsan-gu"},
    {"slug":"samjeon-station","name":"삼전역","lines":['9호선'],"gu":"songpa-gu"},
    {"slug":"samseong-jungang-station","name":"삼성중앙역","lines":['9호선'],"gu":"gwanak-gu"},
    {"slug":"samseong-station","name":"삼성역","lines":['2호선'],"gu":"gangnam-gu"},
    {"slug":"sangbong-station","name":"상봉역","lines":['경의중앙선', '경춘선'],"gu":"jungnang-gu"},
    {"slug":"sangdo-station","name":"상도역","lines":['7호선'],"gu":"dongjak-gu"},
    {"slug":"sanggye-station","name":"상계역","lines":['4호선'],"gu":"nowon-gu"},
    {"slug":"sangil-station","name":"상일동역","lines":['5호선'],"gu":"gangdong-gu"},
    {"slug":"sangsu-station","name":"상수역","lines":['6호선'],"gu":"mapo-gu"},
    {"slug":"sangwangsimni-station","name":"상왕십리역","lines":['2호선'],"gu":"seongdong-gu"},
    {"slug":"sangwolgok-station","name":"상월곡역","lines":['6호선'],"gu":"seongbuk-gu"},
    {"slug":"sapyeong-station","name":"사평역","lines":['9호선'],"gu":None},
    {"slug":"seocho-station","name":"서초역","lines":['2호선'],"gu":"seocho-gu"},
    {"slug":"seodaemun-station","name":"서대문역","lines":['5호선'],"gu":"seodaemun-gu"},
    {"slug":"seokchon-gobun-station","name":"석촌고분역","lines":['9호선'],"gu":"songpa-gu"},
    {"slug":"seokchon-station","name":"석촌역","lines":['8호선', '9호선'],"gu":"songpa-gu"},
    {"slug":"seokgye-station","name":"석계역","lines":['6호선'],"gu":"seongbuk-gu"},
    {"slug":"seolleung-station","name":"선릉역","lines":['2호선', '수인분당선'],"gu":"gangnam-gu"},
    {"slug":"seongsu-station","name":"성수역","lines":['2호선'],"gu":"seongdong-gu"},
    {"slug":"seonjeongneung-station","name":"선정릉역","lines":['수인분당선'],"gu":"gangnam-gu"},
    {"slug":"seonyudo-station","name":"선유도역","lines":['9호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"seoul-station","name":"서울역","lines":['1호선', '4호선', '경의중앙선', '공항철도'],"gu":"yongsan-gu"},
    {"slug":"sinbanghwa-station","name":"신방화역","lines":['9호선'],"gu":"gangseo-gu"},
    {"slug":"sinbanpo-station","name":"신반포역","lines":['9호선'],"gu":"seocho-gu"},
    {"slug":"sinchon-station","name":"신촌역","lines":['2호선'],"gu":"seodaemun-gu"},
    {"slug":"sindaebang-samgeori-station","name":"신대방삼거리역","lines":['7호선'],"gu":"dongjak-gu"},
    {"slug":"sindaebang-station","name":"신대방역","lines":['2호선'],"gu":"dongjak-gu"},
    {"slug":"sindang-station","name":"신당역","lines":['6호선'],"gu":"jung-gu"},
    {"slug":"sindap-station","name":"신답역","lines":['2호선'],"gu":None},
    {"slug":"sindorim-station","name":"신도림역","lines":['1호선', '2호선'],"gu":"guro-gu"},
    {"slug":"singeumho-station","name":"신금호역","lines":['5호선'],"gu":"seongdong-gu"},
    {"slug":"singil-station","name":"신길역","lines":['5호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"sinimun-station","name":"신이문역","lines":['1호선'],"gu":"dongdaemun-gu"},
    {"slug":"sinjeong-negeori-station","name":"신정네거리역","lines":['2호선'],"gu":"yangcheon-gu"},
    {"slug":"sinjeong-station","name":"신정역","lines":['2호선'],"gu":"yangcheon-gu"},
    {"slug":"sinlim-station","name":"신림역","lines":['2호선', '신림선'],"gu":"gwanak-gu"},
    {"slug":"sinmokdong-station","name":"신목동역","lines":['9호선'],"gu":"yangcheon-gu"},
    {"slug":"sinnae-station","name":"신내역","lines":['경춘선'],"gu":"jungnang-gu"},
    {"slug":"sinnonhyeon-station","name":"신논현역","lines":['9호선'],"gu":"gangnam-gu"},
    {"slug":"sinpung-station","name":"신풍역","lines":['7호선'],"gu":None},
    {"slug":"sinsa-station","name":"신사역","lines":['3호선'],"gu":"eunpyeong-gu"},
    {"slug":"sinseol-station","name":"신설동역","lines":['우이신설선'],"gu":None},
    {"slug":"sinyongsan-station","name":"신용산역","lines":['4호선'],"gu":"yongsan-gu"},
    {"slug":"snu-station","name":"서울대입구역","lines":['2호선'],"gu":"gwanak-gu"},
    {"slug":"songjeong-station","name":"송정역","lines":['5호선'],"gu":"seongdong-gu"},
    {"slug":"songpa-station","name":"송파역","lines":['8호선'],"gu":"songpa-gu"},
    {"slug":"songpanaru-station","name":"송파나루역","lines":['9호선'],"gu":"songpa-gu"},
    {"slug":"sookmyung-univ-station","name":"숙대입구역","lines":['4호선'],"gu":None},
    {"slug":"soongsil-univ-station","name":"숭실대입구역","lines":['7호선'],"gu":"dongjak-gu"},
    {"slug":"sports-complex-station","name":"종합운동장역","lines":['9호선'],"gu":"songpa-gu"},
    {"slug":"ssangmun-station","name":"쌍문역","lines":['4호선'],"gu":"dobong-gu"},
    {"slug":"sungshin-univ-station","name":"성신여대입구역","lines":['4호선'],"gu":"seongbuk-gu"},
    {"slug":"suraksan-station","name":"수락산역","lines":['7호선'],"gu":"nowon-gu"},
    {"slug":"suseo-station","name":"수서역","lines":['수인분당선'],"gu":"gangnam-gu"},
    {"slug":"suyu-station","name":"수유역","lines":['4호선'],"gu":"gangbuk-gu"},
    {"slug":"taereung-station","name":"태릉입구역","lines":['7호선'],"gu":"nowon-gu"},
    {"slug":"ttukseom-station","name":"뚝섬역","lines":['2호선'],"gu":"seongdong-gu"},
    {"slug":"ujangsan-station","name":"우장산역","lines":['5호선'],"gu":"gangseo-gu"},
    {"slug":"wangsimni-station","name":"왕십리역","lines":['2호선', '5호선', '수인분당선', '경의중앙선'],"gu":"seongdong-gu"},
    {"slug":"wolgok-station","name":"월곡역","lines":['6호선'],"gu":"seongbuk-gu"},
    {"slug":"wolgye-station","name":"월계역","lines":['1호선'],"gu":"nowon-gu"},
    {"slug":"world-cup-stadium-station","name":"월드컵경기장역","lines":['6호선'],"gu":None},
    {"slug":"yaksu-station","name":"약수역","lines":['6호선'],"gu":"jung-gu"},
    {"slug":"yangcheon-gu-office-station","name":"양천구청역","lines":['2호선'],"gu":"yangcheon-gu"},
    {"slug":"yangcheonhyanggyo-station","name":"양천향교역","lines":['9호선'],"gu":"gangseo-gu"},
    {"slug":"yangjae-station","name":"양재역","lines":['신분당선', '분당선'],"gu":"seocho-gu"},
    {"slug":"yangpyeong-station","name":"양평역","lines":['5호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"yeokchon-station","name":"역촌역","lines":['6호선'],"gu":"eunpyeong-gu"},
    {"slug":"yeoksam-station","name":"역삼역","lines":['2호선'],"gu":"gangnam-gu"},
    {"slug":"yeomchang-station","name":"염창역","lines":['9호선'],"gu":"gangseo-gu"},
    {"slug":"yeongdeungpo-gu-office-station","name":"영등포구청역","lines":['2호선', '5호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"yeongdeungpo-market-station","name":"영등포시장역","lines":['5호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"yeongdeungpo-station","name":"영등포역","lines":['1호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"yeonsinnae-station","name":"연신내역","lines":['3호선', '6호선'],"gu":"eunpyeong-gu"},
    {"slug":"yeouido-station","name":"여의도역","lines":['5호선', '9호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"yeouinaru-station","name":"여의나루역","lines":['5호선'],"gu":"yeongdeungpo-gu"},
    {"slug":"yongdap-station","name":"용답역","lines":['2호선'],"gu":"seongdong-gu"},
    {"slug":"yongdu-station","name":"용두역","lines":['2호선'],"gu":None},
    {"slug":"yongmasan-station","name":"용마산역","lines":['7호선'],"gu":None},
    {"slug":"yongsan-station","name":"용산역","lines":['1호선', '경의중앙선'],"gu":"yongsan-gu"},
]
